- apps/pxweb2/src/app/app.tsx
- libs/pxweb2-ui/.babelrc
- libs/pxweb2-ui/.eslintrc.json
- libs/pxweb2-ui/README.md
- libs/pxweb2-ui/package.json
- libs/pxweb2-ui/project.json
- libs/pxweb2-ui/src/index.ts
- libs/pxweb2-ui/src/lib/pxweb2-ui.module.scss
- libs/pxweb2-ui/src/lib/pxweb2-ui.spec.tsx
- libs/pxweb2-ui/src/lib/pxweb2-ui.tsx
- libs/pxweb2-ui/tsconfig.json
- libs/pxweb2-ui/tsconfig.lib.json
- libs/pxweb2-ui/tsconfig.spec.json
- libs/pxweb2-ui/vite.config.ts
- nx.json
- package-lock.json
- package.json
- tsconfig.base.json
Add a library project to the project, for the ui components.
Co-authored-by:
Per Inge Vaaje
Michael Pande
Kent Mossbaeck
Mikael Nordberg
> PXWEB2-10 Add the base of ui library to project

- apps/pxweb2/src/app/app.tsx
- libs/pxweb2-ui/.storybook/main.ts
- libs/pxweb2-ui/project.json
- libs/pxweb2-ui/src/lib/pxweb2-ui.stories.tsx
- libs/pxweb2-ui/src/lib/pxweb2-ui.tsx
- libs/pxweb2-ui/tsconfig.json
- libs/pxweb2-ui/tsconfig.lib.json
- libs/pxweb2-ui/tsconfig.storybook.json
- nx.json
- package-lock.json
- package.json
Installs storybook with the help of the nx storybook plugin.
Added a simple story to the current, basic component in pxweb2-ui.
> Pxweb2-27 install and setup storybook

- libs/pxweb2-ui/project.json
- package-lock.json
Changed output dir for storybook for test deploy to Netlify
> pxweb2-9 new output directory for storybook build

- .github/workflows/chromatic.yml
PXWEB2-9 publish Storybook on Chromatic on pull request to main on pxweb2-ui path
> PXWEB2-9 publish Storybook on Chromatic

- libs/pxweb2-ui/package.json
- package-lock.json
- package.json
Per Inge Vaaje <60141320+PerIngeVaaje@users.noreply.github.com>
Øyvind Edvardsen
Michael Pande
Kent Mossbaeck
> PXWEB2-75-fix-style-dictionary-build

- CONTRIBUTING.md
- MAINTAINERS.md
Added files for 
- external contributors (CONTRIBUTORS.md) guiding them on how to contribute.
- maintainers (MAINTAINERS.md) guiding the us how to contribute and common agreements that we have.
> Added contrib and mainternes file

- libs/pxweb2-ui/README.md
- package-lock.json
These should be the ones missing, for chromatic to build
> Add missing deps to package-lock.json

- .github/workflows/deploy.yml
- apps/pxweb2/index.html
- apps/pxweb2/vite.config.ts
Should now support [pxtools.github.io/PxWeb2](pxtools.github.io/PxWeb2) as path
> Fix base url for relative react paths

- package.json
Since we need to run tests easily, in various places, we need a script for running all tests easily.
Co-authored-by: Per Inge Vaaje
Co-authored-by: Mikael Nordberg
Co-authored-by: Kent Mossbaeck
Co-authored-by: Michael Pande
> PXWEB2-166 Add command for running tests in all projects

- libs/pxweb2-ui/src/lib/components/Checkbox/Checkbox.spec.jsx
Add a test to check that checkbox handles state correctly, when clicking the checkbox.
Co-authored-by: Per Inge Vaaje <60141320+PerIngeVaaje@users.noreply.github.com>
Co-authored-by: Mikael Nordberg <54406826+MikaelNordberg@users.noreply.github.com>
Co-authored-by: Michael Pande <git@e2e.no>
> PXWEB2-166 Add test for the state of checkbox

- docs/project/Solution.md
- docs/project/overview.md
- mkdocs.yml
Initial project description pages added
> Initial project docs

- docs/overrides/home.html
- mkdocs.yml
This PR contains the following changes:
- Updated the first page with new text for the project.
-  The edit url for pages.
> Fixed first pages

- docs/project/Solution.md
- docs/project/plans.md
- docs/project/process.md
> Kristin glomsas update project doc

- .husky/pre-commit
- package-lock.json
- package.json
Now runs tests and lints on commit.
> Pxweb2 255 precommit hook

- apps/pxweb2/public/locales/no/translation.json
Fix for the "Deselect all" translation in norwegian
PxWeb2-209
> PxWeb2-209-Fix "Deselect all" text in the NO translation

- apps/pxweb2/src/app/components/Footer/Footer.module.scss
La til riktig padding på bunn
Etter
Før
> Fixed padding issue

- apps/pxweb2/public/config/config.js
- apps/pxweb2/public/locales/ar/translation.json
- apps/pxweb2/public/locales/en/translation.json
- apps/pxweb2/public/locales/no/translation.json
- apps/pxweb2/public/locales/sv/translation.json
- apps/pxweb2/public/theme/variables.css
- apps/pxweb2/src/app/app.spec.jsx
- apps/pxweb2/src/app/components/Header/Header.tsx
- apps/pxweb2/src/app/util/config/config.schema.json
- apps/pxweb2/src/app/util/config/configType.ts
- apps/pxweb2/src/i18n/config.ts
> Updated temporary header

- docs/project/Solution.md
- docs/project/overview.md
- docs/project/plans.md
- docs/project/process.md
> Asa arrhen patch 1

- libs/pxweb2-ui/src/lib/components/Button/Button.module.scss
Added cursor to pointer for Button  component
> Set cursor to pointer for Button-component

- apps/pxweb2/src/app/app.tsx
Since we want to refactor the app.tsx file, I thought it would be a good idea to clean it up at bit before hand. This fixes various issues we have with it, like unused imports, unused (old) state etc.
> fix/clean up app.tsx

- README.md
Added a tanks to Chromatic in the project readme file for providing us a open source license for our project.
> Added a thanks to Chromatic in README.md

- apps/pxweb2/public/theme/variables.css
- libs/pxweb2-ui/README.md
- libs/pxweb2-ui/src/lib/components/Alert/Alert.stories.tsx
- libs/pxweb2-ui/src/lib/components/Spinner/Spinner.module.scss
- libs/pxweb2-ui/src/lib/components/Spinner/Spinner.spec.tsx
- libs/pxweb2-ui/src/lib/components/Spinner/Spinner.stories.tsx
- libs/pxweb2-ui/src/lib/components/Spinner/Spinner.tsx
- libs/pxweb2-ui/style-dictionary/src/default_theme.json
Added Spinner component. Also corrected storybook path for Alert
> PXWEB2-216 Added Spinner

- libs/pxweb2-ui/style-dictionary/README.md
- package-lock.json
- package.json
Since we want to keep the project up-to-date, we need to update the packages we use. This updates the 'chromatic'-package for the chromatic cli tool to the latest version, 11.7.1.
> Update chromatic-cli to 11.7.1

- libs/pxweb2-ui/src/lib/components/Skeleton/Skeleton.module.scss
- libs/pxweb2-ui/src/lib/components/Skeleton/Skeleton.stories.tsx
- libs/pxweb2-ui/src/lib/components/Skeleton/Skeleton.tsx
- libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx
> Added skeleton

- Dockerfile
- nginx/conf.d/default.conf
Added a simple Dockerfile for PxWeb2
> Added a Dockerfile

- apps/pxweb2/src/app/components/Presentation/Presentation.module.scss
Minor fix for padding on small screens
> Changed padding above breadcrumb for xsmall and small screens

- apps/pxweb2/public/config/config.js
- apps/pxweb2/src/app/app.tsx
- apps/pxweb2/src/app/util/config/config.schema.json
- apps/pxweb2/src/app/util/config/configType.ts
- libs/pxweb2-api-client/src/core/OpenAPI.ts
The API URL is set in the config.js file instead of being hard coded in OpenAPI.ts
> Moved API URL setting to config.js

- apps/pxweb2/index.html
- libs/pxweb2-ui/src/lib/components/VariableBox/VariableBox.spec.tsx
- libs/pxweb2-ui/src/lib/components/VariableList/VariableList.spec.tsx
preload fonts and fix unit tests for variable box so that it uses a mocked version of react virtuoso
> Pxweb2 384 fix unit tests for variable box

- apps/pxweb2/src/app/components/Presentation/Presentation.tsx
After applying codelist, check for selected values for mandatory failed
> PXWEB2 Fixed error

- .github/workflows/docker-publish.yml
- Dockerfile
Added action publishing docker images to github on releases and on pushes to main
> Added action publishing docker images to github [PXWEB2-350]

- packages/pxweb2/src/mappers/JsonStat2ResponseMapper.ts
Refactoring of the JSONStat2 mapping.
Mapping of variable type implemented.
> +-Feature/pxweb2 397 jsonstat2 mapping

- packages/pxweb2-api-client/src/index.ts
- packages/pxweb2-api-client/src/models/outputFormat.ts
- packages/pxweb2-api-client/src/models/outputFormatParams.ts
- packages/pxweb2-api-client/src/services/TableService.ts
- packages/pxweb2/src/app/context/TableDataProvider.tsx
This updates the generated api-client files to the latest spec.
> Update the generated api-client to the latest spec

- packages/pxweb2/src/app/app.tsx
- packages/pxweb2/src/app/context/AccessibilityProvider.tsx
- packages/pxweb2/src/app/context/useAccessibility.ts
- packages/pxweb2/src/main.tsx
Fixes focus bug in meny & makes sure the provider is used correctly
> Finishing touches 2

- packages/pxweb2/src/app/app.tsx
- packages/pxweb2/src/app/components/NavigationDrawer/NavigationDrawer.tsx
- packages/pxweb2/src/app/components/Selection/Selection.tsx
This fixes some issues with after a merge in the accessibility provider. Some code was duplicate with the code in the app provider, and with the state for the inital navigation item selection when on small screens.
> Fix code for using the accessibility provider

- package-lock.json
- package.json
- packages/pxweb2-ui/package.json
- packages/pxweb2/package.json
Updated minor and patch versions.
> Updated dependecies

- packages/pxweb2-ui/src/lib/components/Checkbox/Checkbox.tsx
Refactor Checkbox component to handle space key for toggling only
> PXWEB2-537 Change value for checkbox with space

- MAINTAINERS.md
This adds a section to the Maintainers file about the current technical debt in the project.
> Adds a section about the current tech debt

- MAINTAINERS.md
Update the technical debt about React and Typescript versions.
> Update techdebt about React/TS versions

- package-lock.json
- package.json
- packages/pxweb2-ui/package.json
- packages/pxweb2/package.json
Used NCU to perform all available package upgrades Tested and ran locally
> chore: upgrade minor/patch versions of dependencies

- packages/pxweb2/src/app/context/TableDataProvider.tsx
Fix for checking if accumulated data is valid or not
> Fix for checking if accumulated data is valid

- packages/pxweb2-ui/src/lib/components/Tag/Tag.module.scss
- packages/pxweb2-ui/src/lib/components/Tag/Tag.stories.tsx
- packages/pxweb2-ui/src/lib/components/Tag/Tag.tsx
> Add subtle variant to Tag component and adjust styles for size variations

- packages/pxweb2/src/app/components/NavigationMenu/NavigationBar/NavigationBar.tsx
- packages/pxweb2/src/app/components/NavigationMenu/NavigationRail/NavigationRail.tsx
Change icons for the Download tab in the navBar/navRail components in the web application.
> Change the icons for downloading in navBar/navRail

- packages/pxweb2/src/app/components/FilterSidebar/FilterSidebar.module.scss
- packages/pxweb2/src/app/pages/StartPage/StartPage.module.scss
- packages/pxweb2/src/app/pages/StartPage/StartPage.tsx
> Adding TableCard to front page.

- .github/workflows/pull-request.yml
- .husky/pre-commit
WIP, adding Mabl job later
:articulated_lorry: Link to branch deployment: https://1a0ae3b8.pxweb2.pages.dev
> Add action for deploying Cloudflare page

- packages/pxweb2-ui/src/lib/components/Alert/Alert.tsx
WCAG fix for failing mabl test
> Refactor Alert component to prevent nested interactive elements

- package-lock.json
This is just the result of "npm audit fix", but it removes some low vulnerabilities.
> Update old dependencies in package-lock

- packages/pxweb2-ui/src/lib/components/Select/Select.tsx
- packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.spec.tsx
- packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx
Variable id and codelist id (if present) will be added to aria-labelledby for search field.
> Add aria-labelledby for search fields in variable box
