PxTools/PxWeb2

package-lock.json

Some developers have started to get `npm install` errors on windows, which seems to be related to incomplete optional dependencies in the package- lock.json file. This is a known issue that is linked to on nx's toubleshooting page: https://github.com/npm/cli/issues/4828
The solution is to delete the `node_modules` folder and the `package-lock.json` file, and then run npm install again to rebuild it.
Per Inge Vaaje <60141320+PerIngeVaaje@users.noreply.github.com>
Rune Johansen

Fix: Rebuild the package-lock.json to fix npm install errors on windows

---

.github/workflows/chromatic.yml
.gitignore
libs/pxweb2-ui/src/lib/pxweb2-ui.module.scss
libs/pxweb2-ui/src/lib/pxweb2-ui.stories.tsx
package-lock.json
package.json

Since we want to test out Chromatic in addition to hosting Storybook on netlify, we need to set up automatic deployments to chromatic's systems also.

Pxweb2 9 install chromatic

---

libs/pxweb2-ui/src/lib/components/Link/Link.module.scss
libs/pxweb2-ui/style-dictionary/src/default_theme.json

Added all semantically named colors

Added all semantically named colors

---

.github/workflows/chromatic.yml

Updates the Chromatic Github Action to run on pushes to the main branch, since chromatic needs this for the UI Reviews to work.
Did not update the workflow to trigger on all pushes, even though that might be what chromatic recommends. We do not know if we will need that yet, and we can change it when we see the need for it.

PXWEB2-39 Run Chromatic action when push to main

---

package-lock.json
package.json

Since the addon was installed as a normal dependency by mistake, we move it to dev dependencies. This also updates it from 7.6.10 to 7.6.12.

Move storybook-a11y to dev dependencies

---

.github/dependabot.yml
README.md

Since we want to have Dependabot help with updating versions of our dependencies, we need to add the configuration file for this.
However, we also have to make sure the dependencies are not updated past what is supported by Nx. Therefore we have opted to use the lockfile-only update strategy, and do manual updates also.

Add dependabot config - dependency version control

---

apps/pxweb2/public/locales/ar/translation.json
apps/pxweb2/public/locales/en/translation.json
apps/pxweb2/public/locales/no/translation.json
apps/pxweb2/public/locales/sv/translation.json
apps/pxweb2/src/@types/resources.d.ts
apps/pxweb2/src/app/app.tsx
apps/pxweb2/src/i18n/useLocalizeDocumentAttributes.ts

The structure of the translation files have been reorganized into sections that follow the structure of the PxWeb user interface.
Hopefully this will make it easy to find the translation text you are looking for.
Only the english translation file is totally updated. The other files only have a minimum of translations.
This is only a draft structure that might come to change later on. It is also possible to divide the translation file into multiple files later on.

Reorganized translation file structure

---

apps/pxweb2/src/app/app.tsx

Since we want to follow best practices as early as possible, we should use the best practices nameing schemes for state variables, even in the early test phase.

Fix the variable name for pxTable state

---

.github/workflows/ci-tests.yml
apps/pxweb2/src/app/app.spec.tsx
package.json

Since we need to run tests as part of our PRs, we need an action that runs these automatically.

Create ci-tests.yml for running tests in pipeline

---

libs/pxweb2-ui/src/lib/components/Select/Select.tsx

To get rid of an extra div that the Select component returns, it has been refactored into being 2 sub components for the variants, instead of 2 functions. Nothing has been done to the logic outside of this.

Refactor Select into 2 sub-components

---

apps/pxweb2/public/theme/variables.css
apps/pxweb2/src/app/components/NavigationRail/NavigationRail.module.scss
libs/pxweb2-ui/src/lib/components/Button/Button.module.scss
libs/pxweb2-ui/src/lib/components/Checkbox/Checkbox.module.scss
libs/pxweb2-ui/src/lib/components/Link/Link.module.scss
libs/pxweb2-ui/style-dictionary/src/default_theme.json

Fixes a couple of CSS variable that were missing part of their names.

Update CSS variable name to fix typo

---

libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxHeader/VariableBoxHeader.module.scss

Since we want the indications for when something can be pressed to be clear, we need to change the mouse cursor when hovering over the clickable header of the VariableBox component.

Fix missing cursor pointer on VariabelBoxHeader

---

libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx

Since we want the language in the application to look correct and professional, we need to make sure we capitalize the first letter of value names in the list of checkboxes in the variable box.
Line 17 was changed by the autoformatter.

Capitalize the first letter of valuename in VB

---

libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxHeader/VariableBoxHeader.module.scss
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxHeader/VariableBoxHeader.tsx

The header of the variablebox should not have an actual h-tag.
Change it to a p-tag with the correct styling.

Fix h-tag mistakenly used in VarBox header element

---

apps/pxweb2/src/app/components/Footer/Footer.module.scss
libs/pxweb2-ui/style-dictionary/README.md

Simple fix for the Footer component missing the same max-width as the Content component

Fix missing max-width on footer

---

apps/pxweb2/src/app/app.tsx
libs/pxweb2-ui/style-dictionary/README.md

Since we only want the EmptyState warning to be rendered at the correct position on the table view, we need to move where the check is being done. This correctly only replaces the table in the table view, and not the entire content view.

Fix empty state to be at the correct position

---

libs/pxweb2-ui/README.md
package-lock.json
package.json

Since we want to keep the project updated, we need to update the chromatic cli package to the latest version.
This will be tested when the pipeline runs for the PR.

Update chromatic-cli to latest

---

apps/pxweb2/public/theme/variables.css
libs/pxweb2-ui/package.json
libs/pxweb2-ui/style-dictionary/build.js
package-lock.json
package.json

Since we want to keep up with major versions of the packages we use, we need to update style-dictionary to v4. We were on v3. We have a pretty light setup, so the process was fairly minor. The main changes are that the lib where it is installed needed to use ES Modules, and that parts of the code is now async.
One change to the output is that it now outputs capital letters for colors, so the variables.css file has many changes.
They also changed the auto-generated comment at the top of that file to not have a timestamp, so it should now not show it has changed everytime the app is run.

Migrate style-dictionary to new major version: 4.0.1

---

libs/pxweb2-ui/style-dictionary/README.md
package-lock.json
package.json

Since we want to keep the packages updated, we need to update them when new major versions are released. It seemed that they removed some older, deprecated namespace loading, which is the breaking change. But the changelog is not clear, and this is based on comments made in the issues in the changelog. I could not find any information about what, if any, breaking changes there are for users updating from v14 to v15.
Tested locally, and seemed to work as expected. Will also test with the preview that is deployed in the pipeline.

Update react-i18next to v15

---

apps/pxweb2/src/app/app.tsx
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx

Since we do not want unnecessary errors and warnings in the console, we need to fix the long standing issues of the warnings for missing keys for the variableBox component. There were two such warnings, and this should fix both(finally).

Fix missing unique keys in variableBox component

---

apps/pxweb2/src/app/context/TableDataProvider.tsx
libs/pxweb2-ui/README.md

Since we do not want unecessary warnings or errors in the console, we need to remove the ones that appear. This fixes two errors when loading the site, because the useEffect in tableprovider for showing the errors in the console was missing a check for an empty string.

Add check for empty errorMsg to tableprovider

---

.github/workflows/chromatic-skip.yml

Since we want to require Chromatic checks to pass before merge to main, we need a workflow to pass those required checks when there are no changes that are related to the UI. As far as I know, there are no ways to test workflows locally before atleast a minimal version is added to main.
The skip workflow is simple, and this is an 'inverted' version of our old workflow. Will need to see if it works in main. Future work and debugging could possibly be done in a new branch, once this file has been added to main so it shows up in GitHub Actions page.

fix/PxWeb2-270: Add new Chromatic workflow to skip if no ui change

---

apps/pxweb2/src/app/app.tsx

Since we want to only get the default selection when you change tables, we need to correctly keep track of the old table id, so we know when to grab the default selection again.
This is a fix for the prior PR that was merged on this issue, PxWeb2-283.

fix/PxWeb2-283: Fix for getting defaultSelection for new table

---

.gitignore
apps/pxweb2/public/theme/variables.css
libs/pxweb2-ui/style-dictionary/src/custom_theme.json

Since we want to test the theme system also, we should have a test-site that uses the custom-theme functionality. This adds some very basic color changes to the test-site for the norwegian api.
The color changes are not supposed to be perfect in this commit, this is to show how it looks, and to check that it works in the pipeline.

Add a custom theme to nor test-site

---

apps/pxweb2/src/app/app.tsx
apps/pxweb2/src/app/context/TableDataProvider.tsx

TableDataProvider now stores a PxTable object instead of a string in context.
In this way we do not need to call JSON.stringify and JSON.parse when storing the PxTable in context and using it in our components which is more efficient.

TableDataProvider stores a PxTable object instead of a string

---

apps/pxweb2/src/app/app.tsx
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBox.tsx
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.spec.tsx
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx

Since we want the newest values shown first when a variable is of type 'time variable', we need to reverse the order of the values for that variable, before we render it. This is possible to keep this simple, because the API always returns the oldest values first.
Also added two tests, to check the order of the checkboxes rendered.

fix/Add so VariableBox reverses values order when it is a time variable

---

apps/pxweb2/src/app/components/Presentation/Presentation.module.scss

The order of the CSS in the presentation component had some media queries before some other code. This counts as having nesting before non-nested CSS, and we get some spam in the console.
"Deprecation Warning: Sass's behavior for declarations that appear after nested rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in `& {}`."
There is also some other spam in the console about SCSS, but it is not related to this. It seems to be related to some defaults being set in Vite.

Fix order of CSS in presentation component

---

apps/pxweb2/index.html

This PR preloads the fonts so that the site loads a bit quicker, and so that we don't get the issue in which we start rendering the site without the required fonts

Preload fonts

---

apps/pxweb2/src/app/components/Selection/Selection.tsx
apps/pxweb2/src/app/context/VariablesProvider.tsx
apps/pxweb2/src/mappers/TableSelectionResponseMapper.spec.ts
apps/pxweb2/src/mappers/TableSelectionResponseMapper.ts
libs/pxweb2-ui/src/index.ts
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBox.tsx
libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx
libs/pxweb2-ui/src/lib/util/util.ts

Since the API now supports a default codelist in the defaultSelection of a table, we need the implementation for showing this when loading a table.
This work was started as part of PxWeb2-198, but was moved to it's own task and branch. Any remaining cleanup will be done during that task.

Feature/Add showing the codelist from the defaultSelection in the VariableBoxes

---

apps/pxweb2/src/app/components/Selection/Selection.tsx
apps/pxweb2/src/mappers/TableMetadataResponseMapper.ts
libs/pxweb2-api-client/src/index.ts
libs/pxweb2-api-client/src/models/ConfigResponse.ts
libs/pxweb2-api-client/src/models/VariablePlacementType.ts
libs/pxweb2-api-client/src/models/VariablesSelection.ts
libs/pxweb2-api-client/src/services/TableService.ts

This updates the API-query for the metadata to ask for the values used in the defaultSelection, and not the standard values.
Also added a try/catch to the mapper to output something when the mapper fails.

Update the API-query for the metadata

---

libs/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx

Set height for Virtuoso list to calculated total height if total is less than 380px high.

PXWEB2-389 Dynamic heights for variable boxes

---

apps/pxweb2/src/mappers/TableSelectionResponseMapper.spec.ts
apps/pxweb2/src/mappers/TableSelectionResponseMapper.ts
libs/pxweb2-api-client/src/models/SelectionResponse.ts
libs/pxweb2-api-client/src/models/VariablesSelection.ts
libs/pxweb2-api-client/src/services/ConfigurationService.ts
libs/pxweb2-api-client/src/services/NavigationService.ts
libs/pxweb2-api-client/src/services/TableService.ts

Updates the API client to the newest version, since we want to update the API.

Update the API-client to the newest version

---

package-lock.json
package.json
packages/pxweb2-ui/package.json
packages/pxweb2/package.json

Removing the Nx packages broke the build step on arm processors, due to the bug in npm with optional architecture dependencies. The same bug I've ran into several times when updating the Nx packages. This fixes those missing dependencies (had to delete node_modules and package-lock.
Also, running the tests after removing Nx, in a clean repo, failed on TypeErrors with getTextBy. This adds a temporary fix by downgrading testing-library/react to the previous major version.

Fix building and testing on macs

---

.github/dependabot.yml

The `lockfile-only` was for NX compatibility i think

Dependabot version updates - Support NPM Workspaces and Docker

---

.vscode/extensions.json

Since we have removed Nx from the repository, we should not recommend the Nx Console extension for VSCode.

Remove Nx Console from recommended repo extensions

---

package-lock.json
package.json

This plugin was left when we removed Nx, and during that process removed cypress.

Remove unused eslint plugin for cypress

---

packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx
packages/pxweb2-ui/src/lib/components/VariableBox/utils.spec.ts
packages/pxweb2-ui/src/lib/components/VariableBox/utils.ts
packages/pxweb2-ui/src/lib/util/util.spec.ts
packages/pxweb2-ui/src/lib/util/util.ts

This moves the groupings last when there are both groupings and value
aggs among the codelists. Also added some tests, and minor refactor.

Fix/pxweb2-198: Show groupings last in codelists

---

eslint.config.mjs

This fixes an issue where sometimes the output directory for storybook isn't moved. Which meant the lint rules that run before commits would lint inside the generated storybook folder. This was a problem since there were many issues to our lint rules in there. It was allready ignored by git, so I see no reason to not just ignore it for linting too.

fix/Add storybook-static to lint ignore

---

.sonarcloud.properties
packages/pxweb2-ui/src/index.ts
packages/pxweb2-ui/src/lib/components/Alert/Alert.spec.tsx
packages/pxweb2-ui/src/lib/components/Modal/Modal.spec.tsx
packages/pxweb2-ui/src/lib/components/Spinner/Spinner.spec.tsx
packages/pxweb2-ui/src/lib/components/VariableBox/VariableBox.spec.tsx
packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.spec.tsx
packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxHeader/VariableBoxHeader.spec.tsx
packages/pxweb2-ui/src/lib/components/VariableList/VariableList.spec.tsx
packages/pxweb2-ui/src/lib/util/testing-utils.ts
packages/pxweb2/src/app/app.spec.tsx
packages/pxweb2/src/app/components/ContentTop/ContentTop.spec.tsx
packages/pxweb2/src/app/components/NavigationMenu/NavigationBar/NavigationBar.spec.tsx
packages/pxweb2/src/app/components/NavigationMenu/NavigationRail/NavigationRail.spec.tsx

This fixes the spam we have had in the terminal related to react-i18next and the useTranslate function. It has been quite spammy, making the testing results hard to read.
Took some troubleshooting to get it to work, but made a mocking function in the ui library, and the export it to the web app to use it there too. The lines for importing and using them are at the top of the files, because they need to be ran before importing the other components that use the function. This seems clearer and easier to deal with than trying to figure out which import line needs to be moved below the others.
Also fixed some small issues with missing variables in the tests where I saw them.

Add mocking in test for useTranslate

---

packages/pxweb2-ui/tsconfig.lib.json
packages/pxweb2-ui/tsconfig.storybook.json
packages/pxweb2/tsconfig.app.json
packages/pxweb2/tsconfig.spec.json

This fixes the errors we have in the tsconfig files from the old types from NX that were left. After this there should not be many more times where we have the red 'error' indicator in our IDEs from config files. One exception is the one file with a test part, that causes an error.

Remove the last types from NX in the projecct

---

package.json
packages/pxweb2-api-client/package.json
packages/pxweb2-ui/package.json
packages/pxweb2/package.json
packages/pxweb2/vite.config.ts

This adds the line '"type": "module"' to the package.json files that are missing it as of now. It cleans up the messages we get when we build the projects. There were several places where it complained that we built it using the old "require()" way. This made reading the terminal output more difficult than it needs to be.
It also adds some formatting to one vite.config.ts file, but nothing functional in it has changed.
Not sure if we need the '"type": "module"' line in the root project, so leaving it for now.

Fix missing type-module in package.json files

---

packages/pxweb2-ui/src/lib/util/setupTests.ts
packages/pxweb2-ui/vitest.config.ts
packages/pxweb2/test/setupTests.ts
packages/pxweb2/vitest.config.ts

This is the second attempt at mocking the useTranslate function from react-i18next. The first time broke the dev environment, but lead to other fixes and to the beginning of this fix. Adds a setupTests file to both the web application and the ui-library. Tested it, and it seems to work fine now. Dev environment runs fine, and the terminal is not spammed with react-i18next errors when running tests.
Please do test this, since we (I) do not want to break something in main again :D

Fix mocking of react-i18next's useTranslate

---

packages/pxweb2-ui/src/lib/components/Checkbox/Checkbox.module.scss
packages/pxweb2-ui/src/lib/components/Checkbox/Checkbox.tsx
packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.module.scss
packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx

Focus should now look as intended in variablebox
Focus should now work as intended in variablebox
Fixed pretty unfortunate bug in which colliding Ids made the focus jump from one variablebox to another

Last focus fix

---

packages/pxweb2-ui/.storybook/main.js
packages/pxweb2-ui/src/lib/components/Checkbox/Checkbox.module.scss
packages/pxweb2-ui/src/lib/components/Table/Table.module.scss
packages/pxweb2-ui/src/lib/components/Typography/BodyShort/BodyShort.module.scss
packages/pxweb2-ui/src/lib/components/Typography/Ingress/Ingress.module.scss
packages/pxweb2-ui/src/lib/global.scss
packages/pxweb2-ui/src/lib/text-styles.scss
packages/pxweb2/src/styles.scss

This fixes how we create our own font-family in the project. The font-family was initially created so we had 3, one for each font-weight. This leads to issues with browser user-agents, that automatically try to add boldness etc. to h1 tags and similar. For us, all the titles were too bold. Now the font-families are merged into one, with the font-weights: 400, 500 and 700. The site looks the same in chrome and safari.

Fix PxWeb2 font-family and font-weights

---

.github/release.yml

It's from the last example on https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Separate features and depencencies in release notes

---

packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxHeader/VariableBoxHeader.tsx

Since we have implemented custom keyboard navigation for opening/closing the variableboxes, we have to prevent that function from triggering the normal auto-scrolling for the spacebar.

Prevent autoscrolling when opening variableboxes

---

package-lock.json
package.json
packages/pxweb2-ui/package.json
packages/pxweb2/package.json

This update the project dependencies that are minor and patch as of now. There was an issue with Storybook 8.5.3 -> 8.5.6, where it failed on some mismatch between dependency versions with its own dependencies. Deleting and rebuilding the package-lock.json file fixed this issue.

Update project dependencies - minor and patch

---

.gitignore
packages/pxweb2-ui/src/lib/components/Modal/Modal.spec.tsx
packages/pxweb2-ui/src/lib/components/Modal/Modal.tsx
packages/pxweb2-ui/src/lib/components/Radio/Radio.spec.tsx
packages/pxweb2-ui/src/lib/components/Radio/Radio.tsx
packages/pxweb2-ui/src/lib/components/Select/Select.module.scss
packages/pxweb2-ui/src/lib/components/Select/Select.spec.tsx
packages/pxweb2-ui/src/lib/components/Select/Select.tsx

This adds the keyboard navigation and focus marking to the Select and modal in the variableBox. It refocuses the Select when the modal closes.

Add keyboard nav and focus to the Select in VarBox

---

package-lock.json
package.json

This adds the missing types for node to the base of the project, which is inherited to the different projects. This should clear up some errors in some config files.

Add missing node types to base package.json

---

packages/pxweb2-ui/src/lib/components/Table/testData.ts

This adds missing (but empty) fields to the table's testData file. It does not improve/expand/change the tests themselves. This is only to remove some spam during the buildprocess.

Add missing (but empty) fields to table testdata

---

package-lock.json

This updates the package versions in package-lock to remove 2 vulnerabilities, with 'npm audit fix'.

Update dependencies in package-lock

---

packages/pxweb2/src/app/components/NavigationDrawer/NavigationDrawer.module.scss
packages/pxweb2/src/app/components/NavigationDrawer/NavigationDrawer.tsx

This fixes:
- Position on the NavigationDrawer when skipToMain is focused on mobile
- Autoscrolling when spacebar is used to click the Hide button in the VariableBox

Fix/pxweb2-540: Two small fixes for keyboard nav/focus marking

---

packages/pxweb2/src/app/pages/TableViewer/TableViewer.module.scss

This re-adds the gap for the contentAndFooterContainer for desktops, to fix the current bug where this gap is missing.

Fix the spacing in TableView for main content

---

packages/pxweb2/src/i18n/formatters.tsx

This removes old comments that override the typechecking for Intl options in the i18next formatters. They are no longer needed since the correct types seem to be updated in TypeScript now (they were missing before).

Remove old comments that override Intl options ts

---

packages/pxweb2/public/config/config.js
packages/pxweb2/src/app/util/config/config.schema.json
packages/pxweb2/src/app/util/config/configType.ts

Since we need to have a number that indicates the maximum number of cells we support in the TableView component, and the api-calls it makes. We need to add a field to the web app config that can be configured and used for this purpose.
Later we might add functionality so that this setting can be directly gotten from the api also/instead.
This is only adding this field, not using it anywhere yet. But I tested it and made sure the config validation fails if it is missing.

Add maxDataCells to web app config

---

packages/pxweb2-ui/src/index.ts
packages/pxweb2-ui/src/lib/shared-types/valueDisplayType.ts
packages/pxweb2-ui/src/lib/shared-types/variable.ts
packages/pxweb2/src/app/components/Selection/Selection.tsx
packages/pxweb2/src/app/util/utils.spec.ts
packages/pxweb2/src/app/util/utils.ts
packages/pxweb2/src/mappers/JsonStat2ResponseMapper.spec.ts
packages/pxweb2/src/mappers/JsonStat2ResponseMapper.ts

Since we want the ability to change codelists, we need to update the function that parses the new codelist metadata for a variable to properly handle the ValueDisplayType and value label texts. This adds similar parsing as the Json2Mapper.
Small refactor to extract shared functionality. If we decide to redo/change how we get the metadata when changing codelists, some of this might have to be redone/undone again.

fix: Variable's values' txts when changing codelists

---

packages/pxweb2/src/mappers/JsonStat2ResponseMapper.ts

This seems to have gone missing. Re-adding the correct type.

Fix wrong type in Json2mapper

---

package-lock.json
packages/pxweb2/package.json
packages/pxweb2/src/app/components/ErrorBoundry/ErrorBoundry.spec.tsx
packages/pxweb2/src/app/components/ErrorPage/ErrorPage.spec.tsx
packages/pxweb2/src/app/components/ErrorPage/ErrorPage.tsx
packages/pxweb2/src/app/components/Header/Header.tsx
packages/pxweb2/src/app/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
packages/pxweb2/src/app/components/LanguageSwitcher/LanguageSwitcher.tsx
packages/pxweb2/src/app/components/Selection/Selection.tsx
packages/pxweb2/src/app/util/language/getLanguagePath.spec.tsx
packages/pxweb2/src/app/util/language/getLanguagePath.ts
packages/pxweb2/src/i18n/config.ts
packages/pxweb2/src/main.tsx
packages/pxweb2/test/setupTests.ts

Since we need to support several languages in the project, we need to add language persistence. What complicates this is that a table can be available in only one language, even though several can be supported for the entire site. And we also need it to work when people share links with other people.
This adds an optional language part to the url, and it uses the fallback language if that part is missing. This means that urls like '/sv/table/tableid' and '/table/tableid' both will work. Since it seems unlikely a site will change its default/fallback language.
I installed the i18next package for detecting browser languages, but set it up to only check for path, and to not cache the values. Since we only want the language in the URL to matter, and to avoid any situations where a user has an …

Add language to url for language persistance

---

packages/pxweb2-ui/src/lib/components/Table/Table.tsx
packages/pxweb2-ui/src/lib/components/Table/cubeHelper.ts
packages/pxweb2-ui/src/lib/shared-types/pxTableData.ts
packages/pxweb2/src/mappers/JsonStat2ResponseMapper.spec.ts
packages/pxweb2/src/mappers/JsonStat2ResponseMapper.ts

Datacells with numbers returned from API could have a status connected. If so the status should be shown together or instead of the number

Show status in datacells if provided

---

packages/pxweb2/public/locales/ar/translation.json
packages/pxweb2/public/locales/no/translation.json
packages/pxweb2/public/locales/sv/translation.json

This adds the missing formatting translation keys for the sv, no and ar languages. This was not needed before, because we defaulted to the en language. It is needed now, since we want to add the ability to change which language is the default language.
This is needed to change the default languages in the two test sites.

Fix missing translation keys in non-Eng languages

---

packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxHeader/VariableBoxHeader.tsx

Id for alert is only included if alert is present.

Fix for missing id in aria-labelledby attribute

---

packages/pxweb2-ui/package.json
packages/pxweb2-ui/src/index.ts
packages/pxweb2-ui/src/lib/components/ContentBox/ContentBox.module.scss
packages/pxweb2-ui/src/lib/components/ContentBox/ContentBox.spec.tsx
packages/pxweb2-ui/src/lib/components/ContentBox/ContentBox.stories.tsx
packages/pxweb2-ui/src/lib/components/ContentBox/ContentBox.tsx
packages/pxweb2-ui/src/lib/components/VariableList/VariableList.module.scss
packages/pxweb2/src/app/components/NavigationDrawer/NavigationDrawer.module.scss
packages/pxweb2/src/app/components/NavigationDrawer/NavigationDrawer.tsx
packages/pxweb2/src/app/components/Selection/Selection.tsx

This adds the contentbox component to the library, which we can use to wrap the different operations we are going to have in the sidebar in the web app.
I am a bit unsure if it should be added to the web app components, or be added in the ui library like I have done.
Also added some basic tests and stories, and updated the NavigationDrawer to better fit the intended use.

Add ContentBox component

---

package.json
packages/pxweb2-api-client/custom/request.ts
packages/pxweb2-api-client/src/core/request.ts
packages/pxweb2-api-client/src/models/Table.ts

Use custom request.ts file that works for binary formats, instead of using generated request.ts file.
When adding "--request ./packages/pxweb2-api-client/custom/request.ts" to the generate api-client script, no request.ts file will be generated. Instead this custom file will be used and placed in the folder./packages/pxweb2-api-client/src/core folder

Use custom request.ts file that works for binary formats

---

package-lock.json
package.json
packages/pxweb2-ui/package.json
packages/pxweb2/package.json

The current installation of the different packages for i18next, are a bit inconsistent and missing. Some are installed in the web app, another is installed in the ui lib, and the i18next main package is missing entirely. This fixes the packages installations by installing them in the root package.json, so they can be used in the web app and ui lib as needed.
We can move them into specific packages later if we need to.

Fix the installation of the i18next packages

---

packages/pxweb2/src/app/context/AppProvider.tsx
packages/pxweb2/src/app/pages/TableViewer/TableViewer.tsx

This changes when the NavDrawer is opened by default on initial table page load. Since we found issues with focus being hidden behind it, it was decided that a better solution for keyboard users is to not start in a state where focus can be hidden. Now only shows it by default on larger than the large breakpoint.
Considered adding a simpler check in TableViewer, but decided to expand the solution for checking window width in the AppProvider. To be consistent with previous solutions.

Change when NavDrawer is open by default

---

packages/pxweb2-ui/src/lib/components/VariableBox/VariableBox.tsx
packages/pxweb2-ui/src/lib/components/VariableBox/VariableBoxContent/VariableBoxContent.tsx
packages/pxweb2-ui/src/lib/components/VariableList/VariableList.tsx
packages/pxweb2/src/app/components/Selection/Selection.tsx
packages/pxweb2/src/app/components/Selection/selectionUtils.spec.ts
packages/pxweb2/src/app/components/Selection/selectionUtils.ts

This adds the logic for adding default values, when changing codelists for mandatory variables. The values chosen is limited to the first value, but the code should be easily extendable to be expanded later. This is why I chose to have the logic for adding the defaults seperated from adding codelist to variables. Any extra processing should not have a significant impact, since we are only mapping over variables here, and not values.
Also updated the tests.

Add first value when changing codelist for mandvar

---

packages/pxweb2/src/app/pages/StartPage/StartPage.tsx

Ensures new API call is made when language is changed

Fix: changing start page language did not reload table data

---

.github/workflows/create-release.yml

the zip command is sensitive to the relative path of the files included, and needs to be run from the correct directory in order to not include the folder hierarchy in the archive contents.

Creates a package with only the contents of the dist folder

---

packages/pxweb2-ui/vite.config.ts
packages/pxweb2/vite.config.ts

Removed Sass legacy API support according to the Vite migration guide to v7.

Remove deprecated vite config code
